apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: springboot-app
  namespace: java-app
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      microservice: api
      app: java-app
  template:
    metadata:
      labels:
        microservice: api
        app: java-app
    spec:
      containers:
        - name: springboot-app
          image: gowthamarumugam/java-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "v2"
            - name: COLOR
              value: "blue"
          readinessProbe:
            httpGet: /health
          startupProbe:
            httpGet: /health
          livenessProbe:
            httpGet: /health
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {}
        - setWeight: 60
        - pause: {}
        - setWeight: 80
        - pause: {}
        - setWeight: 100