# .github/workflows/ci.yml
name: Java CI

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Run reusable composite action
        id: java_build
        uses: NullPointerWorks/trivy-image-scan-action/.github/actions/action.yaml@main
        with:
          java-version: "17"
          build-command: "mvn -B clean verify"
