name: update ssl certificate in kubernetes
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update certificate.yaml'
  workflow_dispatch:
jobs:
  update-certificate:
    environment: production
    name: Update SSL Certificate in Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # - name: Set up kubectl
      #   uses: NullPointerWorks/setup-kubectl@main
      #   with:
      #     azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      #     resource-group: ${{ vars.RESOURCE_GROUP_NAME }}
      #     cluster-name: ${{ vars.AKS_CLUSTER_NAME }}
      - name: minikube start
        env:
          tls_key: ${{ secrets.TLS_KEY }}
          tls_crt: ${{ secrets.TLS_CRT }}
        run: | 
          minikube start --driver=docker
          kubectl apply -f ./manifests/namespace.yaml
          kubectl get namespaces
          echo "$tls_key" > tls.key
          echo "$tls_crt" > tls.crt
          kubectl create secret tls gowtham-tls --key tls.key   --cert tls.crt -n java-app
          kubectl get secrets/gowtham-tls -n java-app
